name: CI/CD

on:
  pull_request:
    branches:
      - base-state

  release:
    types:
      - created

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install makeself shunit2 xmlstarlet jq
      
      - name: Run script from repository root
        run: |
          cd ~/work/LAMWManager-linux/LAMWManager-linux
          ls

      - name: Run tests
        run: bash ~/work/LAMWManager-linux/LAMWManager-linux/lamw_manager/tests/run_tests

      - name: Build setup
        run:  bash  ~/work/LAMWManager-linux/LAMWManager-linux/lamw_manager/assets/build-lamw-setup

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get the version from the commit message
        run: |
          cd ~/work/LAMWManager-linux/LAMWManager-linux
          for version in $(git log --pretty=format:'%s');do if echo $version |  grep -o -E 'v[0-9]+\.[0-9]+\.[0-9]+'; then break; fi; done
          if [ "$version" = ""]; then
          exit 1
          fi

      - name: Create tag and release
        run: |
          cd ~/work/LAMWManager-linux/LAMWManager-linux
          git tag -a $version -m "Release $version"
          git push origin $version

          gh release create $version -t "Release $version" -n "Release notes for $version" /tmp/lamw_manager_setup.sh
