name: CI/CD

on:
  pull_request:
    types:
      - closed

    branches:
      - v0.6.x

  release:
    types:
      - created

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install makeself shunit2 xmlstarlet jq
      
      - name: Run script from repository root
        run: |
          cd ~/work/LAMWManager-linux/LAMWManager-linux
          ls

      - name: Run tests
        run: bash ~/work/LAMWManager-linux/LAMWManager-linux/lamw_manager/tests/run_tests

      - name: Build setup
        run: |
          cd ~/work/LAMWManager-linux/LAMWManager-linux/lamw_manager/assets
          bash -x ~/work/LAMWManager-linux/LAMWManager-linux/lamw_manager/assets/build-lamw-setup

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Get tag
        run: |
          cd ~/work/LAMWManager-linux/LAMWManager-linux
          headers_file=~/work/LAMWManager-linux/LAMWManager-linux/lamw_manager/core/headers/lamw_headers
          version=$(grep "^LAMW_INSTALL_VERSION=" $headers_file  | awk-F= '{ print $2 }' | sed 's/"//g')
          echo "$version" > ~/lamw-tag.txt

      - name: Create tag and release
        run: |
          version=$(<~/lamw-tag.txt)
          echo $version
          git tag -a $version -m "Release $version"
          git push origin $version
          gh release create $version -t "Release $version" -n "Release notes for $version" /tmp/lamw_manager_setup.sh
